
# DataSource Config
spring:
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        username: root
        password: gozapdev
        url: jdbc:mysql://127.0.0.1:3306/demo?useUnicode=true&characterEncoding=utf8&useAffectedRows=true&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true
mybatis-plus:
    mapper-locations: classpath*:/mapper/*.xml
    global-config:
        db-config:
            # 逻辑删除的字段名字
            logic-delete-field: isDeleted
            logic-delete-value: 1
            logic-not-delete-value: 0
    configuration:
        map-underscore-to-camel-case: true
        # 控制台打印ql
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

