// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Hello.proto

package com.jadson;

public interface PersonOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.jadson.Person)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string username = 1;</code>
   */
  java.lang.String getUsername();
  /**
   * <code>string username = 1;</code>
   */
  com.google.protobuf.ByteString
      getUsernameBytes();

  /**
   * <code>int32 age = 2;</code>
   */
  int getAge();
}
